### ISSUE TITLE
Bool props seems to cause an error

### ISSUE THREAD

**Issue by regiscamimura** [oarepo/vue-query-synchronizer#11] opened 2021-03-04 21:26 UTC
I have these in my router:

```
{
        path: "query",
        component: Search,
        name: "search",
        meta: {
          query: {
            query: "string:",
            page: "int:1",
            sort: "string:",
            verified: "bool:false",
            location: "string:"
          },
        },
      },
}
```

Whenever I type something in my <input v-model="$query.location"> I get an error for 

```
TypeError: Cannot read property 'toString' of null
    at Vue.eval (vue-query-synchronizer.esm.js?a9ce:516)
    at Watcher.run (vue.runtime.esm.js?2b0e:4568)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)
```

Apparently, the `verified` bool prop has a null value and them `null.toString()` causes an error

**Comment by mesemus** [comment] 2021-03-06 13:27
Hi Regis,

I'm trying to reproduce the bug but no success so far. 
Please can you describe your environment - browser and vue version etc?

I've added branch `issues/2` - can you check it out, run `yarn serve` 
and go to `http://localhost:8090/2` to see if the problem is still there?

Thanks,

ms.

**Comment by stevelacey** [comment] 2022-01-16 09:55
I am not reliably able to replicate the problem, but it does happen, and seems to involve multiple steps mutating the query in order to exercise it.

This is the fix that Regis went with: https://github.com/regiscamimura/vue-query-synchronizer/commit/7ca36f9827665fec5e3ae465022907330cc333b9

The issue is that `existingQuery[k]` is `undefined`, and based on my quick read of what's happening around it, it seems reasonable that it can't be assumed that `existingQuery[k]` is a stringable.

This resolves the issue in a way that keeps the strict check intact:

```js
const val = newQuery[k] !== null ? newQuery[k].toString() : null
const existingVal = existingQuery[k] !== null && existingQuery[k] !== undefined ? existingQuery[k].toString() : null
if (val !== existingVal) {
```

**Comment by mesemus** [comment] 2022-01-25 07:35
Steve, thanks, merged into the vue-2 branch and a release is at npmjs - version 2.5.0

**Closed by mesemus** 2022-01-25 07:35 UTC

**Comment by stevelacey** [comment] 2022-01-25 09:55
@mesemus thanks! 👏
